### ISSUE TITLE
Support *.pbtxt files

### ISSUE THREAD

**Issue by dmadisetti** [wfxr/protobuf.vim#1]
Hey, cool project- I like the styling. Any thoughts on handling .pbtxt files as well?

Also happy to fork this, but wanted to make an issue first.

**Comment by wfxr** [comment]
Hi @dmadisetti 

> Any thoughts on handling .pbtxt files as well?

I'm not familar with `.pbtxt` but will be glad to accept your contribution if you want to add support for this!

**Comment by dmadisetti** [comment]
Using [this plugin](https://github.com/dmadisetti/.dotfiles/blob/master/vim/plugins.vim#L67) with [this patch](https://github.com/dmadisetti/.dotfiles/blob/master/patches/pbtxt.vim.patch) to make it consistent with this coloring.

Was looking at how [hexmode](https://github.com/fidian/hexmode) changes binary into a vim buffer to see if it was possible to handle dealing with `*.pb` files as well, but decided it wasn't worth it (protoc does some weird things).

Looks like there are some other plugins out there but simpler is better in my books, and the combination of plugins is good enough.
